- name: configure mysql server
  hosts: mysql
  become: yes   #belongs to remote server
  vars_files:                       #for ansible_vault
  - /var/expense/credentials_mysql.yaml     #this is in ansible server,so it needs root & read access -->@ sudo chmod +r /var/expense/credentials_mysql.yaml
  roles:
  - mysql