- name: install nginx server
  ansible.builtin.package:
    name: nginx
    state: present
- name: start nginx server
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: import tasks from common role
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

# - name: remove html directory       # # here we use "common"
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: absent
# - name: create html directory
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: directory

# - name: download the frontend code
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
#     dest: /tmp/frontend.zip

- name: extract the code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip #by default ansible thinks this is in ansible server
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copy expense conf    ##copy only works for files without variables , so here we use template
  ansible.builtin.template:        #ansible.builtin.copy
    src: expense.conf.j2       #src: expense.conf
    dest: /etc/nginx/default.d/expense.conf
  notify: 
  - Restart nginx

# - name: restart nginx
#   ansible.builtin.service:
#     name: nginx
#     state: restarted